name: Auto Update MD File

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour

jobs:
  update_md_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update MD file
        run: echo "$(date)" > README.md
      - run: git config user.name "2010johnlee"
      - run: git config user.email "2010johnlee@gmail.com"
      - run: git commit -am "Auto-update MD file"
      - run: git push
