name: Check Google Drive File

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour

jobs:
  check_drive_file:
    runs-on: ubuntu-latest

    env:
      GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with your desired Python version

      - name: Run Python Script
        run: |
          echo "$GOOGLE_DRIVE_CREDENTIALS" > credentials.json
          python update_path.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json
