name: Check Google Drive File

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every hour on the hour

jobs:
  check_drive_file:
    runs-on: ubuntu-latest

    env:
      GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with your desired Python version
          
      - name: Install Dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Python Script
        run: |
          echo "$GOOGLE_DRIVE_CREDENTIALS" > credentials.json
          python scripts/update_path.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json

      - name: Commit and Push Changes
        run: | #python creates README_temp, if it is different, then update; if not, then do nothing. log activity in log.md.
          if ! cmp -s README_temp.md README.md; then
            env TZ=PDT date >> log.md
            echo "File updated. <br />" >> log.md
            mv README_temp.md README.md
            git config user.name "2010johnlee"
            git config user.email "2010johnlee@gmail.com"
            git commit -am "README.md"
            git push
          else
            env TZ=PDT date >> log.md
            echo "File not updated. <br />" >> log.md
          fi
          git config user.name "2010johnlee"
          git config user.email "2010johnlee@gmail.com"
          git commit -am "log.md"
          git push
